ebaysite/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :views

  get 'profile', to: 'users#profile'
  root to: 'users#profile'
  

  devise_for :users
  resources :users
  resources :products do
  	resources :bids
  end
end

ebaysite/app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  validate :has_errors?

  def has_errors?
    @product = Product.find(self.product_id)
    @min_bid = @product.min_bid
    if @product.bids.all.length == 0
      more_than_min_bid?
    else
      @winner_bid = @product.bids.order("amount DESC").first
      @winner_amount = @winner_bid.amount
      @min_bid= @product.min_bid
      if more_than_min_bid?
      elsif reached_deadline?(@product)
      else is_bigger_bid?(@min_bid,@winner_amount)
      end
    end
  end

  def more_than_min_bid?
    if amount.to_i < @min_bid
      errors.add(:field, "Your bid is less than the minimum price.")
    end
  end

  def reached_deadline?(product)
    if Time.now >= product.deadline
      errors.add(:field, "Deadline not yet.")
    end
  end

  def is_bigger_bid?(min_bid,winner_amount)
    if amount.to_i < winner_amount || amount.to_i == winner_amount
      errors.add(:field, "Your bid must be larger than the current highest bid.")
    end
  end
end

ebaysite/app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_many :bids
	
	validates :title, :description, :deadline, :min_bid, presence: true
	validates :description, length: { maximum: 2000 }
	validates :title, length: { maximum: 100 }
	validates :description, uniqueness: true
	
end

ebaysite/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
	has_many :products
	has_many :bids
	validates :name, :email, :password, presence: true
	validates :name,:email, length: { maximum: 500 }
	validates :email,:name, uniqueness: true
end

ebaysite/app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

ebaysite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

ebaysite/app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def index
    @product = Product.where(id: params[:product_id])[0]
  end
  
  def new
    @bid = Bid.new
  end

  def create
    user = User.where(email: params[:bid][:user])[0]
    amount = params[:bid][:amount]
    if !user.nil? && user == current_user
      @bid = Bid.create(amount: amount, user_id: user.id, product_id: params[:product_id].to_i )
      @product = Product.find(@bid.product_id)
        render :index
    else 
      render :error 
    end
  end
end

ebaysite/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ApplicationHelper
  before_action :logged_in_user

  def index
    @products = Product.all
    @user = current_user
  end

  def show
    @product = Product.find(params[:id])
    @bid = Bid.new
    @sorted_bids = @product.bids.order("amount DESC")
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to products_path
    else
      render :error
    end
  end

  def edit 
    @product = Product.find(params[:id])
   
  end

   def update 
     Product.find(params[:id]).update(product_params) 
    redirect_to products_path
   end

  def product_params
    params.require(:product).permit(:title,:description,:deadline,:min_bid, :user_id)
  end

  def destroy
  end
end

ebaysite/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def profile
    @user = current_user
    render 'users/profile'
  end
end

ebaysite/app/helpers/application_helper.rb
module ApplicationHelper
  def show_user_name(id)
    User.where(id: id)[0].name
  end

  def logged_in?
       !current_user.nil?
  end

   # Confirms a logged-in user.
  def logged_in_user
      unless logged_in?
         flash[:danger] = "You must be logged in."
         redirect_to new_user_session_path
      end
  end
end

ebaysite/app/helpers/bids_helper.rb
module BidsHelper
end

ebaysite/app/helpers/products_helper.rb
module ProductsHelper
end

ebaysite/app/helpers/users_helper.rb
module UsersHelper
end

ebaysite/app/views/bids/error.html.erb
<h1> Something went wrong! </h1>
<% if @errors.nil? %> 
	<p> Not a valid email</p>
<% else %>
	<% @errors.each do |attr,msg| %>
		<p>Error:<%= msg %> </p>
	<% end %>
<% end %>
<%= link_to "Back", :back %>

ebaysite/app/views/bids/index.html.erb
<% if @product.bids.length == 0 %>
	<p>There are no bids at the moment for <%= @product.title %> </p>
<% else %>
    <% bids = @product.bids.order("amount DESC")%>
    <% if @product.deadline <= Time.now %>
      <h1>Deadline reached! <%= User.find(bids.first.user_id).name %> won with $<%= bids.first.amount %> bid!</h1>
    <% else %>
		<h1>Current bids for product: <%= @product.title %></h1>
		<h1>Bids Dealine: <%= @product.deadline %></h1>
		<h2>Current winner at: <%= bids.first.amount %>$</h2>
		<% bids.each do |bid| %>
			<ul>
				<li>User: <%= User.find(bid.user_id).name %>, Bid: $<%= bid.amount %></li>
			</ul>
		<% end %>
	<% end %>
<% end %>
<br>
<%= link_to "Place bid", product_path(@product) %>
<%= link_to "Back", :back %>

ebaysite/app/views/bids/show.html.erb
<h1>Bids on product: <%= @product.title %></h1>
<h2> Current top bid by <%= @top_user %>, bid: $<%= @winner_bid.amount %> </h2>
<% if @winner_amount.nil? %>
	<% bids = @product.bids.order("amount DESC") %>
	<% bids.each do |item| %>
		<ul>
			<li>User: <%= show_user_name(item.user_id)%></li>
			<li>Bid: $<%=item.amount%></li>
		</ul>
	<% end %>
<% else %>
	<p> Deadline reached!!</p>
	<p>Winner: <%= @winner_user%> </p>
	<p>Bid: $<%= @winner_amount%></p>
<%end%>
<br>
<%= link_to "Back", :back %>

ebaysite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ebaysite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="top_bar">
  <% if user_signed_in? %>
    <p><%= link_to 'Sign out', destroy_user_session_path, method: 'DELETE' %></p>
  <% else %>
    <p>
      <%= link_to 'Sign_up', new_user_registration_path %> | 
      <%= link_to 'Sign_in', new_user_session_path %>
    </p>
  <% end %>
</div>
<%= yield %>

</body>
</html>

ebaysite/app/views/products/edit.html.erb
<h1>Edit product</h1>
<%= form_for @product do |f| %>
	<%= f.label :name %>
	<%= f.text_field :title %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.label :Min_bid %>
	<%= f.number_field :min_bid %>
	<%= f.label :deadline %>
	<%= f.date_field :deadline %>
	<%= f.submit "Save changes" %>
<% end %>
<br>
<%= link_to "Back to Products Home", products_path %>

ebaysite/app/views/products/error.html.erb
<h1> There were some errors </h1>
<% @product.errors.messages.each do |key, value| %>
	<% if key == :title%>
		<% key = :name %>
	<%end%>
	<% if key == :user_id %>
		<% key = :email %>
	<%end%>
	<p> <%= key %>: <%= value[0] %></p>
<% end %>
<%= link_to "Try to add product again", new_product_path %> 
<%= link_to "All Products", products_path %>

ebaysite/app/views/products/index.html.erb
<%= link_to "Add product", new_product_path %>
<h1>Producs to bid on: <% @products.each do |product| %> </h1>
	<% if product.user_id != @user.id %>
		<ul>
			<h2>Product Name: <%=product.title%></h2>
			<li>Product Description: <%=product.description%></li>
			<li>Bid Deadline:<%=product.deadline%></li>

			<%= link_to "Bid for this product!!!", product_path(product.id) %>
		</ul>
	<% end %>
<%end%>
<h1>My products:</h1>
	<% @user.products.each do |product| %> </h1>
	<% if product.id != @user.id %>
		<ul>
			<h2>Product Name: <%=product.title%></h2>
			<li>Product Description: <%=product.description%></li>
			<%= link_to "Edit product", edit_product_path(product) %>
		</ul>
	<% end %>
<% end %>

ebaysite/app/views/products/new.html.erb
<h1>Add a new product</h1>

<%= form_for @product do |f| %>
	<%= f.label :name %>
	<%= f.text_field :title %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.label :Min_bid %>
	<%= f.number_field :min_bid %>
	<%= f.label :deadline %>
	<%= f.date_field :deadline %>


	<%= f.submit "Add Product" %>
<% end %>
<br>
<%= link_to "Add product", new_product_path %> 
<%= link_to "All Products", products_path %>

ebaysite/app/views/products/show.html.erb
<h1>Current Product: <%= @product.title %></h1>
<p> Minimunt bid for this product: $<%= @product.min_bid %></p>
<%= form_for [@product, @bid] do |f| %>
	<%= f.label :amount %>
	<%= f.number_field :amount %>
	<%= f.label "Please, reenter your email" %>
	<%= f.text_field :user %>
	<%= f.submit "Bid for Product" %>
<% end %>

<% if @sorted_bids.length > 0 %>
  <h1>Current highest bid: $<%= @sorted_bids.first.amount %> by <%= User.find(@sorted_bids.first.user_id).name %> <br> (Remeber to bet more money!)</h1>
<% else %>
  <h1>There are no bids for this product yet</h1>
<% end %>

<br>
<%= link_to "See all bids for this product", product_bids_path(@product) %>
<br>
<%= link_to "See other products", products_path %>

ebaysite/app/views/users/index.html.erb
<h1><%= link_to "Add User", new_user_path %></h1>
<h1>Current Users: <% @users.each do |user| %> </h1>
<ul>
	<li><%=user.name%> <%= link_to "User Info", user_path(user)%></li>
	<li><%=user.email%></li>
</ul>
<%end%>

ebaysite/app/views/users/new.html.erb
<h1>Welcome to fakEbay new user</h1>
<%= form_for @users do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :password %>
	<%= f.text_field :password %>
	<%= f.submit "Add User" %>
<% end %>
<br>
<%= link_to "Back", :back %>

ebaysite/app/views/users/profile.html.erb
<% if current_user.nil? %> 
	<% redirect_to  new_user_session_path %>
<% end %>
<h2>Welcome <%= current_user.name %>!</h2>
<h2>You have: <%= current_user.bids.length %> bids </h2>

<p>
<strong>Email:</strong> <%= current_user.email %>
</p>
<%= link_to "See all products and start bidding", products_path %>
<br>
<%= link_to "Edit my account", edit_user_registration_path %>

ebaysite/app/views/users/show.html.erb
<p>User: <%= @user.name %></p>
<p>Products: <%= @user.products.length %></p>
<% if @user.products %>
	<%@user.products.each do |product| %>
	<ul>
		<li>Name: <%= product.name %></li>
	</ul>
	<% end %>
<% end %>
<p>User bids: <%= @user.bids.length %></p>
<br>
<%= link_to "Back", :back %>