timetracking_app/config/routes.rb
Rails.application.routes.draw do
	resources :entries, only: [:edit, :update, :destroy]
	resources :projects, only: [:edit, :update]
   	resources :projects  do 
   		resources :entries, only: [:new, :create]
   end
end

timetracking_app/app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
end

timetracking_app/app/models/project.rb
class Project < ActiveRecord::Base
	
	has_many :entries

	def self.ironFind(value)
		where(id: value).first
	end

	def self.find_last_1_hours
		date = Date.current
		last_1_h = date - 1.hours 
		old_projects = where('created_at > ?', last_1_h)
		old_projects.each do |item|
			puts item.id
			end 
	end
	def self.show_all
		all.each do |item|
			puts item.id
		end
	end


end

timetracking_app/app/models/user.rb
class User < ActiveRecord::Base
	has_many :entries
end

timetracking_app/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @entry = @project.entries.new
  end

  def create
    @project = Project.find(params[:project_id])
    @entry = @project.entries.new(entry_params)
    if @entry.save
      flash[:notice] = "Entry Created Successfully"
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def destroy
    entry = Entry.find(params[:id])
    entry.destroy
    redirect_to action: "show", id: entry.project_id, controller: "projects"
  end
  
  def edit
    @entry = Entry.find(params[:id])
    render :edit
  end

  def update
    @entry = Entry.find(params[:id])
    @entry.update(entry_params)
    redirect_to("/projects")
  end

  private

  def entry_params
    params.require(:entry).permit(:hours, :minutes, :date, :comments)
  end


end

timetracking_app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order("updated_at DESC").limit(10)
  end

  def new
    @project = Project.new
    render :new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project Created Successfully"
      redirect_to project_path(@project.id)
    else
      render :new
    end
  end

  def show
    id = params[:id]
    @project = Project.find(id)
    @entries = @project.entries
  end

  def edit
    @project = Project.find(params[:id])
    render :edit
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to("/projects")
  end

  private
  def project_params
    params.require(:project).permit(:title,:description)
  end

end

timetracking_app/app/controllers/sites_controller.rb
class SitesController < ApplicationController
	def contact
		render :contact
	end
end

timetracking_app/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_helper
    if flash[:alert]
      content_tag :div, class: "message-alert" do
        content_tag :p do
          flash[:alert]
        end
      end
    elsif flash[:notice]
      content_tag :div, class: "message-notice" do
        content_tag :p do
          flash[:notice]
        end
      end
    end
  end
end

timetracking_app/app/helpers/entries_helper.rb
module EntriesHelper
end

timetracking_app/app/helpers/projects_helper.rb
module ProjectsHelper
end

timetracking_app/app/helpers/sites_helper.rb
module SitesHelper
end

timetracking_app/app/views/entries/edit.html.erb
<h1>Edit Entries</h1>
<%= form_for @entry do |f| %>
	<%= f.label :Date %>
	<%= f.date_field :date %>
	<%= f.label :Hours %>
	<%= f.number_field :hours %>
	<%= f.label :Minutes %>
	<%= f.number_field :minutes %>
	<%= f.label :Comments %>
	<%= f.text_area :comments %>
	<%= f.submit "Edit Modified Entries" %>
	<%= link_to "delete" %>
<% end %>

timetracking_app/app/views/entries/new.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>

<h1>Add New Entry </h1>
<%= form_for [@project,@entry] do |f| %>
	<%= f.label :Date %>
	<%= f.date_field :date %>
	<%= f.label :Hours %>
	<%= f.number_field :hours %>
	<%= f.label :Minutes %>
	<%= f.number_field :minutes %>
	<%= f.label :Comments %>
	<%= f.text_area :comments %>
	<%= f.submit "Add Entry" %>
<% end %>

timetracking_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

timetracking_app/app/views/projects/_form.html.erb
<% if project.id.nil? %>
	<% button_name = "Create Project" %>
<% else %>
	<% button_name = "Edit Project" %>
<% end %>

<%= form_for project do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.submit button_name %>
<% end %>

timetracking_app/app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= form_for @project do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.submit "Edit Project" %>
	
<% end %>

timetracking_app/app/views/projects/index.html.erb
<html>
	<head>
		<title>projects</title>
	</head>
	<body>
		<h1>PROJECTS</h1>
		<% @projects.each do |project| %>
		<ul>
			<li><%= link_to(project.title, project_path(project.id))%> updated at: <%=project.updated_at%></li>
			
		</ul>

		<% end %>
		<%= link_to "Create Project", new_project_path %>
	</body>
</html>

timetracking_app/app/views/projects/new.html.erb
<h1>Create Project</h1>
<%= render partial: "form", locals: {project: @project} %>

timetracking_app/app/views/projects/show.html.erb
<%= flash_helper %>

<h1>COUNTRIES</h1>
<h2>Country name: <%= @project.title %></h2>
<p>Description: <%= @project.description %> </p>
<%= link_to "Edit Project", edit_project_path(@project) %>
<p>Entries for project </p>
<% @entries.each do |entry| %>
<ul>
	<li>Project id: <%= entry.project_id %> </li>
	<li>Project comments: <%= entry.comments %></li>
	<li>Project date: <%= entry.date %></li>
	<li>Project hours: <%= entry.hours %></li>
	<li>Project minutes: <%= entry.minutes%></li>
	<%= link_to "Edit Entry", edit_entry_path(entry) %>
	<%= link_to('Delete', entry_path(entry), method: :delete, confirm: 'Are you sure?') %>
</ul>
<% end %>
<%= link_to "Go Back Home", projects_path %>
<%= link_to "Create New Entry", new_project_entry_path(@project) %>

timetracking_app/app/views/sites/contact.html.erb
<p>victorsagristalopez@gmail.com</p>

timetracking_app/app/views/sites/home.html.erb
Hello world!