addressbook/config/routes.rb
Rails.application.routes.draw do
  get "/" => "contacts#index"
  root to: "contacts#index"
  get "/contacts/show_favorites" => 'contacts#show_favorites'
  post "/contacts/find_contact" => "contacts#find_contacts"
  post "/contacts/make_favorite" => "contacts#make_favorite"
  post "/contacts/unfavor_contact" => "contacts#unfavor_contact"

  resources :contacts, :only => [:index, :new, :show]
end

addressbook/app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :email, :address, :phone, presence: true
  validates :name, :email, length: {maximum: 50}
  validates :phone, numericality: {only_integer: true}

  def self.find_contact_from_first_letter(letter)
  	Contact.where('substr(name, 1, 1) = ? OR substr(name, 1, 1) = ?', letter.upcase, letter.downcase)
  end

  def self.make_favorite(id)
  	Contact.find(id).update(state: true)
  end

  def self.unfavor_contact(id)
  	Contact.find(id).update(state: false)
  end

  def self.get_favorites
  	Contact.where(state: true)
  end

end

addressbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

addressbook/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all.sort{|a,b| a <=> b}
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to("/contacts/#{@contact.id}")
    else
      render :new
    end
  end

  def show_favorites
    @contacts = Contact.get_favorites
    render :favorites
  end

  def make_favorite
    Contact.make_favorite(params[:id])
    redirect_to root_path
  end

  def unfavor_contact
    Contact.unfavor_contact(params[:id])
    redirect_to root_path
  end


  def find_contacts
    @contacts = Contact.find_contact_from_first_letter(params[:character])
    render :found_contacts
  end

  private
  def contact_params
    params.require(:contact).permit(:name,:address,:email,:phone)
  end
end

addressbook/app/helpers/contacts_helper.rb
module ContactsHelper
end

addressbook/app/views/contacts/favorites.html.erb
<h1> You are a in our list of favorite contacts! </h1>
<%= link_to "Home", root_path %><br>
<% @contacts.each do |contact| %>
<ul>
	<% if contact.state %>
	<li> Contact Number: <%= contact.id %></li>
	<li> Contact Name: <%= contact.name %></li>
	<li> Contact Address: <%= contact.address %></li>
	<li> Contact Email: <%= contact.email %></li>
	<li> Contact Phone: <%= contact.phone %></li>
	<li> :) </li>
	<% end %>
</ul>
<% end %>
	

addressbook/app/views/contacts/found_contacts.html.erb
<h1> Contacts found </h1>
<% @contacts.each do |contact| %>
	<ul>
		<li><%= contact.name %></li>
		<%= link_to "View Contact", contact_path(contact) %>
	</ul>
<%end%>
<%= link_to "Home", root_path %>

addressbook/app/views/contacts/index.html.erb
<h1> Hello from Rails: Contact List</h1>
<%= link_to "Add Contact", new_contact_path %>
<%= link_to "Favorites", contacts_show_favorites_path %>

<form action="/contacts/find_contact" method="post" enctype="multipart/form-data">
	<label>Search contact by first letter:</label><br>
	<input type='text' name="letter">
</form>

<% @contacts.each do |contact| %>
	<ul>
		<li> Contact Name: <%= contact.name %></li>
		<li> Contact Address: <%= contact.address %></li>
		<li> Contact Email: <%= contact.email %></li>
		<li> Contact Phone: <%= contact.phone %></li>
		<% if contact.state %> 
			<li>FAVORITE :)</li>
			<form action="/contacts/unfavor_contact " method="post" >
				<input type="hidden" name="id" value=<%= contact.id %>>
				<button type="submit">Unfavor</button>
			</form>
		<% else %>
			<form action="/contacts/make_favorite " method="post" >
				<input type="hidden" name="id" value=<%= contact.id %>>
				<button type="submit">Favorite!</button>
			</form>
		<% end %>
	</ul>
<% end %>

addressbook/app/views/contacts/new.html.erb
<% if @contact.errors.messages.present? %>
	<p><%= @contact.errors.messages %></p>
<%end%>
<%= form_for @contact do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :address %>
	<%= f.text_field :address %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :phone %>
	<%= f.text_field :phone %>
	<%= f.submit "Save Contact" %>
<% end %>

<%= link_to "Home", root_path %>

addressbook/app/views/contacts/show.html.erb
<h1>Contact Page</h1>
	<ul>
		<li> Contact Name: <%= @contact.name %></li>
		<li> Contact Address: <%= @contact.address %></li>
		<li> Contact Email: <%= @contact.email %></li>
		<li> Contact Phone: <%= @contact.phone %></li>
		<% if @contact.state %> 
			<li>FAVORITE :)</li>
			<form action="/contacts/unfavor_contact " method="post" >
			<input type="hidden" name="id" value=<%= @contact.id %>>
			<button type="submit">Unfavor</button>
		</form>
		<% else %>
			<form action="/contacts/make_favorite " method="post" >
				<input type="hidden" name="id" value=<%=@contact.id %>>
				<button type="submit">Favorite!</button>
			</form>
		<% end %>
	</ul>
<%= link_to "Home", root_path %>

addressbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Addressbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>